
const __header = require('./header');
const __domething = require('./domething');
const __body_ui = require('./body/ui');
const __body_navigo = require('./body/navigo');

exports.worker_socketio = false ;
exports.postMessage_socketio = (postMessage_data_socketio) => {
  // add pathname to request
  postMessage_data_socketio = Object.assign(postMessage_data_socketio, { path: window.location.pathname });
  if (this.worker_socketio) {
    // worker give object event containing { data: postMessage_data_socketio, .. }
    this.worker_socketio.postMessage(postMessage_data_socketio);
  } else { // use callback
    // giving object containing data like the event
    postMessage_data_socketio = { data: postMessage_data_socketio };
    require('./body/socketio')._onmessage(postMessage_data_socketio, (onmessage_cb_data) => {
        onmessage_common_socketio(onmessage_cb_data);
    });
  }
}

// https://www.jstips.co/en/javascript/detect-document-ready-in-pure-js/
const stateCheck_complete = window.setInterval(() => {
  if ((document.readyState == 'complete') && __header.get_state().done) {
    window.clearInterval(stateCheck_complete);
    // document ready
    //_add_contextmenu_listener();

    //__domething.cleanup_prototypes();
    const stateCheck_cleanup_prototypes = window.setInterval(() => {
      if (__domething.get_state().done.cleanup_prototypes) {
        window.clearInterval(stateCheck_cleanup_prototypes);
        
        __body_ui.init();
        const stateCheck_body_ui_init = window.setInterval(() => {
          if ((typeof __body_ui.get_state().done == 'boolean') && __body_ui.get_state().done) {
            window.clearInterval(stateCheck_body_ui_init);
            
            __body_navigo.init();
            const stateCheck_navigo_init = window.setInterval(() => {
              if (__body_navigo.get_state().done) {
                window.clearInterval(stateCheck_navigo_init);
                
                // SOCKETIO BASE
                if (window.Worker) {
                  const blob_socketio = new Blob( // generated by scripts/make-worker-blobs.js
                    require('./body/socketio.blobparts.bundle.js').blobparts,
                    { type: 'text/javascript' }
                  );
                  this.worker_socketio = new Worker(URL.createObjectURL(blob_socketio));
                  this.worker_socketio.addEventListener('message', (e) => {
                    event.preventDefault(); event.stopPropagation();
                    if (!event.isTrusted) { return false }
                    onmessage_common_socketio(e.data); //
                  }, useCapture = false);
                  this.worker_socketio.addEventListener('messageerror', (e) => {
                    event.preventDefault(); event.stopPropagation();
                    if (!event.isTrusted) { return false }
                    page_main_add('_console', 'onmessageerror_socketio', e);
                  }, useCapture = false);
                  this.worker_socketio.addEventListener('error', (e) => {
                    event.preventDefault(); event.stopPropagation();
                    if (!event.isTrusted) { return false }
                    page_main_add('_console', 'onerror_socketio (worker)', e);
                  }, useCapture = false);
                } else {
                  __body_ui.notification_add("Browser doesn't support Workers ! UI is freezing", 'icon-danger');
                }
                
                // lets init socketio client
                //this.postMessage_socketio({ origin: 'init' });
                this.postMessage_socketio({ origin: 'init' });
            
                
                
                
                
                //console.log(window);
                //console.log(document);
                // TEST BEFORE LOCK
                //print_edit_node(document, 'document');
                //print_edit_node(window, 'window');
                //print_edit_node(navigator, 'navigator');
                //print_edit_node(navigator.clipboard, 'navigator.clipboard');
                //print_edit_node(document.querySelector('head > style'), 'head > style');
                
                //this.check_html_resources();
                
                // KEEP IT AT THE BOTTOM
                // stopPropagation for _eventsType_keep
                const _events_stop_propagation_without_capture = ['click', 'focus', 'focusout'];
                for (let instance in __header._eventsType_keep) {
                  const _nodeinstance = instance == 'window' ? window : document;
                  for (let eventType of __header._eventsType_keep[instance]) {
                    if (typeof _nodeinstance.addEventListener == 'function') {
                      _nodeinstance.addEventListener(eventType, (event) => {
                        event.stopPropagation();
                        if (!event.isTrusted) { return false }
                      }, useCapture = !_events_stop_propagation_without_capture.includes(eventType) ? true : false );
                    }
                  }
                }
                
                //__domething.cleanup_elements();
                const stateCheck_cleanup_elements = window.setInterval(() => {
                  if (__domething.get_state().done.cleanup_elements) {
                    window.clearInterval(stateCheck_cleanup_elements);
                    //__domething.lock_prototypes();
                    const stateCheck_lock_prototypes = window.setInterval(() => {
                      if (__domething.get_state().done.lock_prototypes) {
                        window.clearInterval(stateCheck_lock_prototypes);
                        
                        // TEST AFTER LOCK
                        //print_edit_node(document.querySelector('body > button'), 'body > button');
                      }
                    }, 0); // stateCheck_lock_prototypes
                  }
                }, 0); // stateCheck_cleanup_elements
                // KEEP IT AT THE BOTTOM
              }
            }, 0); // stateCheck_navigo_init
          }
        }, 20); // stateCheck_body_ui_init
      }
    }, 0); // stateCheck_cleanup_prototypes
  }
}, 0); // stateCheck_complete (readyState)


exports.check_html_resources = () => {
  const _resources = {
    links: document.querySelectorAll('link'),
    styles: document.querySelectorAll('style'),
    scripts: document.querySelectorAll('script')
  }
  for (let resourcesType in _resources) {
    for (let resource of _resources[resourcesType]) {
      const _resource_details = `${resource.tagName.toLowerCase()};id=${resource.id ? resource.id : ''};srchref=/${resourcesType == 'scripts'
        ? resource.src
          ? `${resource.src.split('/')[resource.src.split('/').length-1]}:[/]${resource.src.split('/').length-1}`
          : ''
        : resource.href
          ? `${resource.href.split('/')[resource.href.split('/').length-1]}:[/]${resource.href.split('/').length-1}`
          : ''}`
      ;
      const _is_jsheader = (resource.tagName.toLowerCase() == 'script') && resource.id && (resource.id == 'jsheader') && ( __header.IS_FOOSTACK_DEV
        ? (resource.src && (resource.src.split('/')[3] == 'header.js'))
        : !resource.src )
      const _is_jsbody = (resource.tagName.toLowerCase() == 'script') && resource.id && (resource.id == 'jsbody') && ( __header.IS_FOOSTACK_DEV
        ? (resource.src && (resource.src.split('/')[3] == 'body.js'))
        : !resource.src )
      const _is_style = (__header.IS_FOOSTACK_DEV ? resource.tagName.toLowerCase() == 'link' : resource.tagName.toLowerCase() == 'style') && resource.id && (resource.id == 'style') && ( __header.IS_FOOSTACK_DEV
        ? (resource.href && (resource.href.split('/')[3] == 'styles.css'))
        : !resource.href )
      if (!_is_jsheader && !_is_jsbody && !_is_style) {
        __body_ui.notification_add(`Unexpected loaded resource: ${_resource_details}`, 'icon-danger', background_color = 'red');
        __body_ui.page_main_add('_console', `Unexpected loaded resource: ${_resource_details}`, resource.innerHTML, details_as_text_node = true, background_color = 'red');
        resource.remove();
      }
    }
  }
}

const onmessage_common_socketio = (data) => {
  __body_ui.page_main_add('_connection', 'onmessage_common_socketio', data);
  if ((typeof data == 'object') && Object.keys(data).includes('on')) {
    switch (data.on) {
      case "set":
        switch (data.name) {
          case "pub":
            if (!Object.keys(data).includes('err')) {
              __body_ui.page_main_add('_connection', '=========== SIGN:', 'sign the next message content (paste it in the input below and send it)');
              __body_ui.page_main_add('_connection', '=========== MESSAGE:', data.message);
            } else {
              __body_ui.page_main_add('_connection', '=========== OPENPGP PUBLIC KEY NOT VALID:', 'paste your openpgp public key (armored) in the input below and send it');
            }
            break;
        }
        break;
      case "connect":
        document.querySelector("body > footer > aside.right > button > i").classList.replace("icon-color-red", "icon-color-yellow");
        break;
      case "data ack (hns)":
        document.querySelector("body > footer > aside.right > button > i").classList.replace("icon-color-yellow", "icon-color-blue");
        __body_ui.page_main_add('_connection', '=========== LOGIN:', 'type: /login_auto or\n      /login to use your keys');
        break;
      case "data":
        if (data.deserialized_data) {
          if (typeof data.deserialized_data.response == 'object') {
            if ((data.deserialized_data.data == '/login') && Object.keys(data.deserialized_data.response).includes('seed')) {
              __body_ui.page_main_add('_connection', '=========== OPENPGP PUBLIC KEY:', 'paste your openpgp public key (armored) in the input below and send it');
            }
          } else {
            switch (data.deserialized_data.response) {
              case "connected":
                document.querySelector("body > footer > aside.right > button > i").classList.replace("icon-color-blue", "icon-color-green");
                break;
              case "disconnected":
                document.querySelector("body > footer > aside.right > button > i").classList.replace("icon-color-green", "icon-color-blue");
                break;
            }
          }
        }
        break;
      case "disconnect":
        document.querySelector("body > footer > aside.right > button > i").classList.replace("icon-color-green", "icon-color-red");
        document.querySelector("body > footer > aside.right > button > i").classList.replace("icon-color-blue", "icon-color-red");
        document.querySelector("body > footer > aside.right > button > i").classList.replace("icon-color-yellow", "icon-color-red");
        break;
    }
  }
}

const print_edit_node = (_node, _node_name = '_node', _keep = []) => {
    //const _node = document.querySelector('body'); // Document.prototype or something else
    //const _keep = [ // keep getAttribute
    //  "test"
    //]; 
    const isundefined = [];
    const isundefinednotinkeepfn = [];
    const isnullundefined = [];
    const isnotnull = [];
    for (let key in _node) {
      if (!_keep.includes(key)) {
        try {
          //_node[key] = null;
        } catch (e) {}
      }
      try {
        if (_node[key] == 'undefinedprototype') {
          isundefined.push(key);
        } else if (_node[key] == 'undefinednotinkeepfn') {
          isundefinednotinkeepfn.push(key);
        } else if ((_node[key] == null) || (_node[key] == undefined)) {
          isnullundefined.push(key);
        } else {
          isnotnull.push(key);
        }
      } catch (e) {}
    }
    __body_ui.page_main_add('_console', `${_node_name} undefinedprototype`, isundefined);
    __body_ui.page_main_add('_console', `${_node_name} undefinednotinkeepfn`, isundefinednotinkeepfn);
    __body_ui.page_main_add('_console', `${_node_name} null || undefined`, isnullundefined);
    __body_ui.page_main_add('_console', `${_node_name}   => else`, isnotnull);
}


/*
const _add_contextmenu_listener = () => {
  window.addEventListener('contextmenu', (event) => {
    event.preventDefault(); event.stopPropagation();
    if (!event.isTrusted) { return false }
    if (event.target.tagName.toUpperCase() != 'TEXTAREA' && event.target.tagName.toUpperCase() != 'INPUT') {
      const selection = window.getSelection();
      const range = document.createRange();
      range.selectNodeContents(event.target);
      selection.removeAllRanges();
      selection.addRange(range);
      if (window.getSelection().toString().length > 0) {
        // https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText
        console.log(navigator.clipboard.writeText);
        navigator.clipboard.writeText(window.getSelection().toString());
      }
    } else {
      event.target.value = '';
      //event.target.value = await navigator.clipboard.readText();
    }
  }, useCapture = false);
}
*/


/*
window.addEventListener('contextmenu', (event) => {
  event.preventDefault(); event.stopPropagation();
  if (!event.isTrusted) { return false }
  if (event.target.tagName.toUpperCase() != 'TEXTAREA' && event.target.tagName.toUpperCase() != 'INPUT') {
    const selection = window.getSelection();
    const range = document.createRange();
    range.selectNodeContents(event.target);
    selection.removeAllRanges();
    selection.addRange(range);
    if (window.getSelection().toString().length > 0) {
      // https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText
      console.log(navigator.clipboard.writeText);
      navigator.clipboard.writeText(window.getSelection().toString());
    }
  } else {
    event.target.value = '';
    //event.target.value = await navigator.clipboard.readText();
  }
}, useCapture = false);

exports._copy_selection_to_clipboard = () => {
  if (navigator && Object.keys(navigator).includes('clipboard') && Object.keys(navigator.clipboard).includes('writeText')) {
    if (window.getSelection().toString() > 0) {
      navigator.clipboard.writeText(window.getSelection().toString());
    }
  }
}
const _handle_selection = (event) => {
  const selection = window.getSelection();
  const range = document.createRange();
  range.selectNodeContents(event.target);
  selection.removeAllRanges();
  selection.addRange(range);
  __body_ui.global_ui_vars.copy.content = window.getSelection().toString();
}
const _handle_copy_button = (event) => {
  if (window.getSelection().toString().length > 0) {
    if (__body_ui.global_ui_vars.copy.button) {
      __body_ui.global_ui_vars.copy.button.remove();
      __body_ui.global_ui_vars.copy.button = false ;
    }
    const _button = document.querySelector('body > button').cloneNode(deep = false);
    _button.innerHTML = 'COPY';
    _button.classList.add('copy');
    _button.addEventListener('click', (event_button) => {
      event_button.preventDefault(); event_button.stopPropagation();
      navigator.clipboard.writeText(window.getSelection().toString());
      //this._copy_selection_to_clipboard();
      __body_ui.global_ui_vars.copy.button.remove();
      __body_ui.global_ui_vars.copy.button = false ;
    }, useCapture = false);
    __body_ui.global_ui_vars.copy.button = _button;
    event.target.parentNode.appendChild(_button);
  }
}
window.addEventListener('selectstart', (event) => {
  event.preventDefault(); event.stopPropagation();
  //if (!event.isTrusted) { return false }
  _handle_selection(event);
  _handle_copy_button(event);
  console.log(window.getSelection().toString());
}, useCapture = false);
document.addEventListener('copy', (event) => {
  event.preventDefault(); event.stopPropagation();
  //if (!event.isTrusted) { return false }
  event.clipboardData.setData('text/plain', window.getSelection().toString());
}, useCapture = false);
*/