const path = require('node:path');
const fs = require('node:fs');

const __db_blockchain = require('./db/blockchain');
//const __db_memory = require('./db/memory');
const __common_network = require('./common/network');
const __common_crypto = require('./common/crypto');
const __utils_network = require('./utils/network');
const __utils_crypto = require('./utils/crypto');

//require('./db/memory').db.connectivity_peers can contain any peer
require('./db/memory').db.connectivity_peers = [
        { server: '127.0.0.1', port: '8001' }
];

// require('./db/memory').db.default_peers have to contain trusted peers only
if (process.env.FOOSTACK_DEV == "yes") {
    require('./db/memory').db.default_peers = [
        { server: '127.0.0.1', port: '8001' }
        ,{ server: '127.0.0.1', port: '8002' }
        //, { server: '127.0.0.1', port: '8003' }
    ];
} else {
    require('./db/memory').db.default_peers = [
        { server: '127.0.0.1', port: '8001' }
        ,{ server: '127.0.0.1', port: '8002' }
        , { server: '127.0.0.1', port: '8003' } // here production servers
    ];
}


exports.http = require('node:http').createServer( (req, res) => {
    //running npm run build replace process.env.FOOSTACK_DEV by false
    console.log(req.url);
    if (process.env.FOOSTACK_DEV == "yes") {
      const _path_css = path.join(__dirname, 'web/css/styles.bundle.css');
      const _path_js_header = path.join(__dirname, 'web/js/header.bundle.js');
      const _path_js_body = path.join(__dirname, 'web/js/body.bundle.js');
      const _path_html = path.join(__dirname, 'web/index.html');
      const _files = [
          { req: '/styles.css', path: _path_css, type: 'text/css' },
          { req: '/header.js', path: _path_js_header, type: 'text/javascript' },
          { req: '/body.js', path: _path_js_body, type: 'text/javascript' },
      ];
      const req_files_index = _files.map(function(obj) {
        return obj.req;
      }).indexOf(req.url);
      if (req_files_index >= 0) {
        fs.readFile(_files[req_files_index].path, (err, data) => {
          if (err) { console.log(err) }
          res.writeHead(200, __utils_network.get_http_headers(_files[req_files_index].type)); res.write(data); res.end();
        });
      } else {
        fs.readFile(_path_html, (err, data) => {
          if (err) { console.log(err) }
          res.writeHead(200, __utils_network.get_http_headers('text/html')); res.write(data); res.end();
        });
      }
    } else {
        // generated by scripts/make.index.html.js
        res.writeHead(200, __utils_network.get_http_headers('text/html')); res.write(require('./web/index.bundle.html.js').default); res.end('</body></html>');
    }
});

exports.io = require('socket.io')(this.http, { // https://socket.io/docs/v4/server-options/
    transporst: ["websocket"], // ["polling", "websocket", "webtransport"] default value
    allowUpgrades: false, // true default value
    upgradeTimeout: 10000, // 10000ms default value
    maxHttpBufferSize: 1e6, // 1MB default value, (1e8 in case (100MB)) a single char(string) is 2 bytes
    pingInterval: 25000, // 25000ms default value
    pingTimeout: 20000, // 20000ms default value
    cookie: {
        name: __utils_crypto.misc.generate.seed_int(100,1024), //4096 or less
        path: "/", httpOnly: true, sameSite: "strict", secure: false
    }
});

exports.generate_new_uuid = () => {
  require('./db/memory').db.server.uuid = require('uuid').v5('s2s', require('uuid').v4());
  console.log(`\n  => Server init with uuid: ${require('./db/memory').db.server.uuid}\n`);
}

exports.generate_new_openpgp = async () => {
  require('./db/memory').db.server.openpgp = await __common_crypto.openpgp.generate(
    require('./db/memory').db.server.uuid,
    `${require('./db/memory').db.server.uuid}@localhost.local`
  );
  console.log(`\n  => Server init with new openpgp keys\n`);
}


__utils_network.get_port_to_use( async (port) => {
  require('./db/memory').config.network.port = `${port}`;
  this.generate_new_uuid();
  await this.generate_new_openpgp();
  this.http.listen({ port: port }, () => {
    console.log(`\n  => Server init listening on port: ${port}\n`);
    // populate require('./db/memory').db.peers with require('./db/memory').db.default_peers omce
    for (let index = 0; index < require('./db/memory').db.default_peers.length; index++) {
      require('./db/memory').db.peers.push({ server: require('./db/memory').db.default_peers[index].server, port: require('./db/memory').db.default_peers[index].port });
    }
    
    require('./db/blockchain').init();
    require('./controllers/socketio.s2s').init();
    require('./controllers/socketio').init();
    require('./controllers/cron').init();
    /*
    const gen_login_auto_user_openpgpcreds = async () => {
      _openpgpcreds = await require('./common/crypto').openpgp.generate('user', 'user@test.local', armored = true);
      console.log(JSON.stringify(_openpgpcreds));
    }
    gen_login_auto_user_openpgpcreds();
    */
    // stdin as TEST
    process.stdin.setEncoding('utf8');
    process.stdin.on("data", async (input) => {
        const _input = input.toString().split(':');
        if (_input[0] === 'sub') {
          require('./db/blockchain').blockchain_subscribe(_input[1].replace(/\n/g, ''));
        } else if (_input[0] === 'unsub') {
          require('./db/blockchain').blockchain_unsubscribe(_input[1].replace(/\n/g, ''));
        } else if (_input[0] === 'verifychain') {
          // not true maybe to really make it auto (only at init or on demand)
          require('./db/blockchain').verify_chain(_input[1].replace(/\n/g, ''));
        } else if (_input[0] === 'syncchain') {
          require('./db/blockchain').sync_chain({ chain: _input[1].replace(/\n/g, '')});
        } else if (_input[0] === 'print_config\n' || _input[0] === 'pc\n') {
          console.log('require(\'./db/memory\').config');
          console.log(require('./db/memory').config);
        } else if (_input[0] === 'print_sockets\n' || _input[0] === 'ps\n') {
          require('./controllers/socketio.s2s').print_sockets();
        } else if (_input[0] === 'print_peers\n' || _input[0] === 'pp\n') {
          console.log('require(\'./db/memory\').db.peers');
          console.log(require('./db/memory').db.peers);
          console.log('require(\'./db/memory\').db.default_peers');
          console.log(require('./db/memory').db.default_peers);
          console.log('require(\'./db/memory\').db.connectivity_peers');
          console.log(require('./db/memory').db.connectivity_peers);
        } else if (_input[0] === 'print_blacklists\n' || _input[0] === 'pb\n') {
          console.log('require(\'./db/memory\').db.blacklist');
          console.log(require('./db/memory').db.blacklist);
          console.log('require(\'./db/memory\').db.blacklist_web');
          console.log(require('./db/memory').db.blacklist_web);
        } else if (_input[0] === 'print_server_state\n' || _input[0] === 'pstate\n') {
          console.log('require(\'./db/memory\').db.state');
          console.log(require('./db/memory').db.state);
        } else if (_input[0] === 'addpeer') {
          await require('./db/memory').db.set.peer(require('./db/memory').db.peers.length, { server: _input[1], port: _input[2].replace(/\n/g, '') }); // ADD PEER ONCE
          await require('./controllers/socketio.s2s').init_ioclient_from_outside(require('./db/memory').db.peers.length-1); 
        } else {
          if (_input.length == 1) {
            _input[1] = _input[0];
            _input[0] = require('./db/blockchain').chainhash;
          }
          const _block = require('./db/blockchain').new_block(data = _input[1], chain = _input[0]);
          const _data = { blockchain_method: 'new_block', block: _block, chain: _input[0] }
          console.log(`\n\nSENDING New block: ${_block.block}`);
  
          //console.log(require('./db/memory').db);
  
          for (let index = 0; index < require('./db/memory').db.peers.length; index++) {
              if (require('./db/memory').db.peers[index].socket.connected) {
                  
                  require('./db/memory').db.peers[index].socket.emit('data', await __common_network.serialize(
                      require('./db/memory').db.server.uuid, require('./db/memory').db.server.openpgp, _data, require('./db/memory').db.peers[index].pub
                  ));
                  
                  //    used to test serialize/deserialize
                  //require('./db/memory').db.peers[index].socket.emit('data', 'datatest');
                  /*
                  require('./db/memory').db.peers[index].socket.emit('data', await __common_network.serialize(
                      require('./db/memory').db.server.uuid, require('./db/memory').db.server.openpgp, _data, false
                  ));
                  */
              }
          }
        }
    }); // end process.stdin.on
  }); // end http.listen
}); // end get_port_to_use



//exports.is_production = process.pkg ? true : process.env.NODE_ENV == 'production' ? true : false;
//const cwd = this.is_production ? process.cwd() : __dirname;

//used to display pkg snapshot content
// require('../../scripts/walk').walk(path.join(__dirname, '../../../'), function(err, results) {
//     if (err) throw err;
//     console.log(results);
// });



//L'acte de persécution est lié à plusieurs mécanismes psychologiques et sociaux. 
//Le persécuteur passionné : Les psychiatres décrivent le persécuteur comme un « passionné » dont la haine est une colère chronique, souvent liée à des délires de revendication, de jalousie ou d'exaltation. 
//La projection défensive : Le sentiment de persécution se propage par la tendance à projeter ses propres pulsions ou conflits sur un groupe, créant un sectarisme qui justifie la violence envers les opposants. 
//La domination par la puissance : Certains dispositifs de pouvoir visent à exciter la « puissance d'agir » du sujet (son élan de défense) pour mieux le dominer et l'anéantir, transformant ses réflexes de survie en torture. 

//Paradoxalement, ce sentiment de dépossession est souvent entretenu par le système même qu'il critique. 
//Le rituel de l'illusion : La participation électorale est vécue comme un « piège à consentement » où l'on valide sa propre dépossession en choisissant entre des options qui ne changent rien aux structures de pouvoir réelles. 
//L'addiction à la frustration : Plus la dépossession est grande, plus la rage est intense, et plus l'adhésion à des leaders promettant de « tout casser » devient forte.  C'est un cercle vicieux où la frustration alimente le soutien à ceux qui promettent la vengeance, même si ces derniers renforcent souvent la dépossession réelle une fois au pouvoir. 

//Nous sommes reconnaissants pour l'usage des signaux visuels et sonores (de courtoisie) mis en œuvre par les services de police et de secours pour mener à bien leur mission (TOP secret avec best args for JT).

// ======##*****+****+***+**#****#***+*#***+++++++++%%%#--+#%%%%%%#.:#%%+.=#=:=%%%#**%%#*#=.#%#%##%%#%%
// +=+==+##*********+*+++####**#******+++++++++++++*%###--+%%%%%%%%#..:##=:-+::#%%%=+##%#=.-%*###*-*%%%
// ====+=*##******+*+++*+*#********++==++++++++++++#%%%#:=%%%%%#+%%%*...-==::::-#%#.+#**-.:####+..#%%%%
// ==+++++##*+***+++*+*=********+=++**########*+++*#%%##%%%##%%%%=+%%#::.::=-:::#*-.=##=.:=*#*..:##+++=
// +=+++++*%#*+***+++*=*+****++++++*#####%%%##########-@%%%#==+#%%%=+%+.:.::==-:=-.:*%-::-#-:.:-+%%%%%+
// +*++++++*%#+**+++++++*+====++++*#*#%%%%%%%%%%#%%####%%%%#==-:-=+#%+++::::::=-::*=*-:::--.::=%%%%%%#-
// +++==+++*#%#+++++*+===========+*####%%###%%%@%%%%###%%%%%+=====-:::+*-::::::=---:::::-+:::=%%%%%%%++
// ==+==+=++%%%#+++=============+**########%%#****######%%%%%*=======+==::::::::+--:::::==::*%%%#*=-*-+
// =+++++=++%@%*================+######%%%#*=---=*##%%%%%%%%%%%*===+==+=+++::::::+-:--:-+::-::.:+%%#-++
// =+*++++*++=================+*####%%@@%%+:..-::-=+****+++===+*#%#+====++++=:::.==:-:-+=+*+=#%%%%*-+++
// +++***====================*####*+%%#*+:..:::-----------====---==+#%%%#*+====-.-=--=+=+#%%%%%%%%==+==
// +++======================+###%*=+*=::::::---:----=--------------====*%%%%%%+-::=-++#%#####+-:----===
// +========================*#%#+===:.::::::::::::---------------=+*+=-===+%%%%+++-:::::----=-===-=++++
// =-=======================#*+====:::::::::::::::-----:---------==---------=++---===---=====+++++++**=
// ==============================-::::::....:..:::::----------------=+*#####*+==---===+***####*#*++****
// =============================:::::..........:::::::--::::-----=+**#%#####%%%%%*#%%%%#####%%%%=-+*+**
// ==========================+-..............:::::::::::::::--==**#####%%%%%#%%%%%%#####%%%%%%%%+=****+
// ==============++=========+-::....:..::::::::.::..:::::::---=+*##########*%@%@@@%%%%%%%%%%@@%%*=+****
// ========================+--#=-:......:..::::::.....:::::--==*########%%##%@@@@@%@@@@@@@@%%%%%#*+#*#*
// =======================+=.+%%=-.......:::::-:::......::--==+*#########%##%@@@@@%%@@@@@@@@@@%%#*=**+=
// =======================+-.*%#*......:..:::::.....:..:::-==+*###########%%%@@@@@%#%@@@@@@@@@%%%#++***
// =======++++=+++===++====..=%%=........::...::..::::.::--=+*#*##########%%%@@@@@%%%%@@@@@@@@@%%%%#*+=
// ======-:::::::-===+++++-..:=-:......::..::::.:::.::::-=++**##############%%@@@@@%%%%%@@@@@@%%%%%%#**
// ======--------===---=+=............::..::....:::::-=++****###########%###%%@@@@@%##%@@@@@@%%%%%###*+
// ==++===:::::::---:---:....::....:::...:.......::-==++**##########%%%%%%###%@@@@@%%#%@@@@@%%%%%%##*++
// +++++=#+----:----:::.....:...:::::..::..:...:.:=====+*#########%%%%%%%%###%@@@@@@%#%@%%%%%%%%%#***+*
// +++++=+++=-==-----........:::-:::....:::::::-----=++*#***####%%%%%%%%%%#*#%@@@@@@%##@%%%%%%%%#**#***
// ++++++++=-====--:....::::::--::::::.:::::==++****#*#####**###%%%@@@@@%%#*#%@@@@@@%##%%%%%%%%*=---=*+
// =++++++++=*#**+-..:::::::.:::::-:::..:::**#%%+=##%@%%@%%**####%@@@@@@@%###%%%%######%%%%%%#=-------=
// +++++++++=+#%#=:::::.....:::..:-::::::::-=#%%%@@%%%%%%%%%#####%%@@@@%%##%%%%#%%%#**##%%%*====-------
// +++++++++=++=:.....:::::::::::::--:::::::--=+++##%%%##**########%%%#####%%%%##*+++*##%*======-------
// +++++++++=:.....:::::::::::::::::::::::::-::::-=-==+*************###*###%%*+==-=+#%%#+======--------
// +++=+++=:..:.::::::::::-:::::-::::::::::---:::---==++******************##*====+#%%%*======----------
// +==+++=...::::::-:::::---::::-:::::::::::::::::-==+++*****+************#*==+%%%%%@+==+===----:------
// +++++=.:-=++=----:::---:-::::::::::::::::::::::=++++++++****************=*%@@%@@%++++++=---:::---=--
// ++++=.=%%%##*+=-:-==+=----::::::::::::::::::::-=+++++***************+**=*%@@@@@#*+=+===---:::::--:--
// :::::#%%%%%%%##**+**+=-----:::::-::::::::::::-=++*+****#***********++=+*#@@@@%*++==+=-:-:::::::::-:-
// ::::=%###%%%%%%%###*++==---:--::::::::::::::-=+++*+*#####*##***++++*+*%%@@@%*=-===-=-:-::-::::::::--
// :::.=%%####%%%%%%%%%#*+------::::::::::::::--==---==---------==-=*%%%%@@@%=-:---=-=+=:::::::::::::-=
// :::.-#%#####%%%%%%%%%#+----=-::::::::::::::----=======----:::-=#@@@%@@@%+-::-:-:-:==::::::::::::::==
// :::--=#%#%%%%%%%%%%#*+---=++-=-:::::::::----=======-----::-=*%@@@@@@@@#-:::::::::-:::::::::::::::--=
// -:::::=#%%%%%%%%%#*==------------:::::::=++==----------=+#*%@%@@@@@@#-:::::::::::::::.:::::::::::--=
// ::::::::=**+****=-------:--::--:::-=+***%%%%#**######%**%@***@@@#+--::::::::::::::::.:::::::::::---=
// ::--::::::-==+-::---:-::-:-::::-++########%%%%%%%%%%%%@#*%@%**=-:-:::::::::::::::::.:::::::.::::--==
// =:..:..::::::::------:-----::::-=***#####+:-*##%%%%%%##*+++-::::::::::::::::::::::.::::::.:::----==-
// ++++-::::-----:-------:::.:::::::--*####*+:.......::::--::::::::::::::::::::::::::..:.:::::::------.
// ++=+=+==+++++=-----:::::..:::.:::::-=*##*+-..:..::::::::::::::::::::::::::::::::....:::::-:-------.:
// +===========++++==----:::::...:::::::-*#*+-..........::::::::::::::::::::.::.:...::.:::::--------:..
// ===========*+=++##*+==--::::::::::::::-##*-.........::::::::.::::::.:::::::::::.::.::::::--------:..
// ==========++++=+*#+=====--::::::::::::::#*+:........:..::::::::::::::::::::::::::.:::::::::----::...
// Pott <3
